# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      dhcp6: false
      addresses:
        - 10.245.83.107/25
      routes:
        - to: default
          via: 10.245.83.1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
    enp4s0:
      dhcp6: false
      addresses:
        - 10.0.0.1/24
      routes:
        - to: 10.0.0.0/24
          via: 10.0.0.1
