function pengchchoec(varargin);
% pengchchoec( [...] );
% CH4 CH4 OE Current
h = timeplot({'CH4_OE_OutputCurrent'}, ...
      'CH4 CH4 OE Current', ...
      'Current', ...
      {'CH4\_OE\_OutputCurrent'}, ...
      varargin{:} );
