function pengcocoqclt(varargin);
% pengcocoqclt( [...] );
% CO2 CO2 QCL Temp
h = timeplot({'CO2_QCL_T','CO2_QCL_Set_T','CO2_QCL_Sink_T'}, ...
      'CO2 CO2 QCL Temp', ...
      'Temp', ...
      {'CO2\_QCL\_T','CO2\_QCL\_Set\_T','CO2\_QCL\_Sink\_T'}, ...
      varargin{:} );
