function pengcoecoqcle(varargin);
% pengcoecoqcle( [...] );
% CO2 Errors CO2 QCL Errors
h = timeplot({'CO2_QCL_ErrorNumber','CO2_QCL_ErrorInstance','CO2_QCL_ErrorParameter'}, ...
      'CO2 Errors CO2 QCL Errors', ...
      'CO2 QCL Errors', ...
      {'CO2\_QCL\_ErrorNumber','CO2\_QCL\_ErrorInstance','CO2\_QCL\_ErrorParameter'}, ...
      varargin{:} );
