function pengcocooes(varargin);
% pengcocooes( [...] );
% CO2 CO2 OE Status
h = timeplot({'CO2_OE_DevStatus'}, ...
      'CO2 CO2 OE Status', ...
      'Status', ...
      {'CO2\_OE\_DevStatus'}, ...
      varargin{:} );
