function pengbsmes(varargin);
% pengbsmes( [...] );
% Bay Stale ME Stale
h = timeplot({'Bay_Stale'}, ...
      'Bay Stale ME Stale', ...
      'ME Stale', ...
      {'Bay\_Stale'}, ...
      varargin{:} );
