function penggdccm(varargin);
% penggdccm( [...] );
% GD ccm
h = timeplot({'LoCal_VolFlow','HiCal_VolFlow'}, ...
      'GD ccm', ...
      'ccm', ...
      {'LoCal\_VolFlow','HiCal\_VolFlow'}, ...
      varargin{:} );
