function penggdhks(varargin);
% penggdhks( [...] );
% GD HK Status
h = timeplot({'LoCal_Status','HiCal_Status'}, ...
      'GD HK Status', ...
      'Status', ...
      {'LoCal\_Status','HiCal\_Status'}, ...
      varargin{:} );
