function pengcpchks(varargin);
% pengcpchks( [...] );
% CPC HK Status
h = timeplot({'C_AbsP_Status','C_DiffP_Status'}, ...
      'CPC HK Status', ...
      'Status', ...
      {'C\_AbsP\_Status','C\_DiffP\_Status'}, ...
      varargin{:} );
