function pengbbhc(varargin);
% pengbbhc( [...] );
% Bay Bay Heat Current
h = timeplot({'Bay_Heat_OutputCurrent'}, ...
      'Bay Bay Heat Current', ...
      'Current', ...
      {'Bay\_Heat\_OutputCurrent'}, ...
      varargin{:} );
