function penggdhkmbar(varargin);
% penggdhkmbar( [...] );
% GD HK mbar
h = timeplot({'LoCal_P','HiCal_P'}, ...
      'GD HK mbar', ...
      'mbar', ...
      {'LoCal\_P','HiCal\_P'}, ...
      varargin{:} );
