function pengcosfgs(varargin);
% pengcosfgs( [...] );
% CO2 Stale Fwd Gas Stale
h = timeplot({'Fwd_Gas_Stale'}, ...
      'CO2 Stale Fwd Gas Stale', ...
      'Fwd Gas Stale', ...
      {'Fwd\_Gas\_Stale'}, ...
      varargin{:} );
