function pengcosmes(varargin);
% pengcosmes( [...] );
% CO2 Stale ME Stale
h = timeplot({'CO2_Stale'}, ...
      'CO2 Stale ME Stale', ...
      'ME Stale', ...
      {'CO2\_Stale'}, ...
      varargin{:} );
