function penggdhkstale(varargin);
% penggdhkstale( [...] );
% GD HK Stale
h = timeplot({'LoCal_Stale','HiCal_Stale','GD_Stale'}, ...
      'GD HK Stale', ...
      'Stale', ...
      {'LoCal\_Stale','HiCal\_Stale','GD\_Stale'}, ...
      varargin{:} );
