function pengchchoev(varargin);
% pengchchoev( [...] );
% CH4 CH4 OE Voltage
h = timeplot({'CH4_OE_OutputVoltage'}, ...
      'CH4 CH4 OE Voltage', ...
      'Voltage', ...
      {'CH4\_OE\_OutputVoltage'}, ...
      varargin{:} );
