function pengcpchkt(varargin);
% pengcpchkt( [...] );
% CPC HK Torr
h = timeplot({'C_AbsP_P','C_DiffP_P'}, ...
      'CPC HK Torr', ...
      'Torr', ...
      {'C\_AbsP\_P','C\_DiffP\_P'}, ...
      varargin{:} );
