function penggdnccm(varargin);
% penggdnccm( [...] );
% GD nccm
h = timeplot({'LoCal_MassFlow','LoCal_Set','HiCal_MassFlow','HiCal_Set'}, ...
      'GD nccm', ...
      'nccm', ...
      {'LoCal\_MassFlow','LoCal\_Set','HiCal\_MassFlow','HiCal\_Set'}, ...
      varargin{:} );
