function pengcofgc(varargin);
% pengcofgc( [...] );
% CO2 Fwd Gas Current
h = timeplot({'Fwd_Gas_OutputCurrent'}, ...
      'CO2 Fwd Gas Current', ...
      'Current', ...
      {'Fwd\_Gas\_OutputCurrent'}, ...
      varargin{:} );
