function pengcocoqcls(varargin);
% pengcocoqcls( [...] );
% CO2 CO2 QCL Status
h = timeplot({'CO2_QCL_DevStatus'}, ...
      'CO2 CO2 QCL Status', ...
      'Status', ...
      {'CO2\_QCL\_DevStatus'}, ...
      varargin{:} );
