function pengqcli_c_statstatus(varargin);
% pengqcli_c_statstatus( [...] );
% QCLI C stat status
h = ne_dstat({
  'QCLI_C_present', 'QCLI_C_CS', 11; ...
	'QCLI_C_laser', 'QCLI_C_s', 12; ...
	'QCLI_C_cordte', 'QCLI_C_s', 11; ...
	'QCLI_C_cmderr', 'QCLI_C_s', 13; ...
	'QCLI_C_cksum', 'QCLI_C_s', 14; ...
	'QCLI_C_busy', 'QCLI_C_s', 15; ...
	'QCLI_C_loc', 'QCLI_C_s', 3; ...
	'QCLI_C_lot', 'QCLI_C_s', 4; ...
	'QCLI_C_dot', 'QCLI_C_s', 5; ...
	'QCLI_C_waveerr', 'QCLI_C_s', 8; ...
	'QCLI_C_ready', 'QCLI_C_s', 9 }, 'status', varargin{:} );
