function pengtsspc(varargin);
% pengtsspc( [...] );
% Temps SSP C
h = timeplot({'SSP_C_T_FPGA','SSP_C_T_HtSink'}, ...
      'Temps SSP C', ...
      'SSP C', ...
      {'SSP\_C\_T\_FPGA','SSP\_C\_T\_HtSink'}, ...
      varargin{:} );
