function pengqcli_c_statmode(varargin);
% pengqcli_c_statmode( [...] );
% QCLI C stat mode
h = timeplot({'QCLI_C_mode'}, ...
      'QCLI C stat mode', ...
      'mode', ...
      {'QCLI\_C\_mode'}, ...
      varargin{:} );
