function pfocalgdsgdse(varargin);
% pfocalgdsgdse( [...] );
% GDS Entran
h = timeplot({'Cal_Hi_HP','Cal_Hi_LP','Cal_Lo_HP','Cal_Lo_LP','Ref_HP','Ref_LP'}, ...
      'GDS Entran', ...
      'Entran', ...
      {'Cal\_Hi\_HP','Cal\_Hi\_LP','Cal\_Lo\_HP','Cal\_Lo\_LP','Ref\_HP','Ref\_LP'}, ...
      varargin{:} );
