function pfocalqcliqclics(varargin);
% pfocalqcliqclics( [...] );
% QCLIQCLI C Scan
h = timeplot({'SSP_C_Num'}, ...
      'QCLIQCLI C Scan', ...
      'Scan', ...
      {'SSP\_C\_Num'}, ...
      varargin{:} );
