function pfocalhkmecocoqclc(varargin);
% pfocalhkmecocoqclc( [...] );
% ME CO2 CO2 QCL Current
h = timeplot({'CO2_QCL_OutputCurrent'}, ...
      'ME CO2 CO2 QCL Current', ...
      'Current', ...
      {'CO2\_QCL\_OutputCurrent'}, ...
      varargin{:} );
