function pfocalqcli_qcli_c_statfifodep(varargin);
% pfocalqcli_qcli_c_statfifodep( [...] );
% QCLI C stat fifodep
h = timeplot({'QCLI_C_fifodep'}, ...
      'QCLI C stat fifodep', ...
      'fifodep', ...
      {'QCLI\_C\_fifodep'}, ...
      varargin{:} );
