function pfocalcoecort(varargin);
% pfocalcoecort( [...] );
% CO2 Rov T
h = timeplot({'CO2_RefInT','CO2_RefOutT'}, ...
      'CO2 Rov T', ...
      'Rov T', ...
      {'CO2\_RefInT','CO2\_RefOutT'}, ...
      varargin{:} );
