function pfocalbbhkn(varargin);
% pfocalbbhkn( [...] );
% Bay HK Nreads
h = timeplot({'GDS_Bay_Nreads'}, ...
      'Bay HK Nreads', ...
      'Nreads', ...
      {'GDS\_Bay\_Nreads'}, ...
      varargin{:} );
