function pfocalchchct(varargin);
% pfocalchchct( [...] );
% CH4 Cell T
h = timeplot({'CH4_Cell1T','CH4_Cell2T','CH4_Cell3T'}, ...
      'CH4 Cell T', ...
      'Cell T', ...
      {'CH4\_Cell1T','CH4\_Cell2T','CH4\_Cell3T'}, ...
      varargin{:} );
