function pfocalmecofgs(varargin);
% pfocalmecofgs( [...] );
% ME CO2 Fwd Gas Status
h = timeplot({'Fwd_Gas_DevStatus'}, ...
      'ME CO2 Fwd Gas Status', ...
      'Status', ...
      {'Fwd\_Gas\_DevStatus'}, ...
      varargin{:} );
