function pfocalhkmebfgc(varargin);
% pfocalhkmebfgc( [...] );
% ME Bay Fwd Gas Current
h = timeplot({'Fwd_Gas_OutputCurrent'}, ...
      'ME Bay Fwd Gas Current', ...
      'Current', ...
      {'Fwd\_Gas\_OutputCurrent'}, ...
      varargin{:} );
