function pfocalgpsgpshknngga(varargin);
% pfocalgpsgpshknngga( [...] );
% GPS HK N N GGA
h = timeplot({'GPS_N_GGA'}, ...
      'GPS HK N N GGA', ...
      'N GGA', ...
      {'GPS\_N\_GGA'}, ...
      varargin{:} );
