function pfocalmoedmoeais(varargin);
% pfocalmoedmoeais( [...] );
% uD MOE AI Stat
h = timeplot({'uD_MOE_stat'}, ...
      'uD MOE AI Stat', ...
      'AI Stat', ...
      {'uD\_MOE\_stat'}, ...
      varargin{:} );
