function pfocaldacscoft(varargin);
% pfocaldacscoft( [...] );
% CO2 Flow T
h = timeplot({'CO2_SamInT','CO2_SamOutT','CO2_RefInT','CO2_RefOutT'}, ...
      'CO2 Flow T', ...
      'Flow T', ...
      {'CO2\_SamInT','CO2\_SamOutT','CO2\_RefInT','CO2\_RefOutT'}, ...
      varargin{:} );
