function pfocalmechschoes(varargin);
% pfocalmechschoes( [...] );
% ME CH4 Stale CH4 OE Stale
h = timeplot({'CH4_OE_Stale'}, ...
      'ME CH4 Stale CH4 OE Stale', ...
      'CH4 OE Stale', ...
      {'CH4\_OE\_Stale'}, ...
      varargin{:} );
