function pfocalmechchoes(varargin);
% pfocalmechchoes( [...] );
% ME CH4 CH4 OE Status
h = timeplot({'CH4_OE_DevStatus'}, ...
      'ME CH4 CH4 OE Status', ...
      'Status', ...
      {'CH4\_OE\_DevStatus'}, ...
      varargin{:} );
