function pfocalcoedcoehkain(varargin);
% pfocalcoedcoehkain( [...] );
% uD COE HK AI N
h = timeplot({'uD_COE_N'}, ...
      'uD COE HK AI N', ...
      'AI N', ...
      {'uD\_COE\_N'}, ...
      varargin{:} );
