function pfocalmebcooet(varargin);
% pfocalmebcooet( [...] );
% ME Bay CO2 OE Temp
h = timeplot({'CO2_OE_T','CO2_OE_Set_T','CO2_OE_Sink_T'}, ...
      'ME Bay CO2 OE Temp', ...
      'Temp', ...
      {'CO2\_OE\_T','CO2\_OE\_Set\_T','CO2\_OE\_Sink\_T'}, ...
      varargin{:} );
