function pfocalmechchoec(varargin);
% pfocalmechchoec( [...] );
% ME CH4 CH4 OE Current
h = timeplot({'CH4_OE_OutputCurrent'}, ...
      'ME CH4 CH4 OE Current', ...
      'Current', ...
      {'CH4\_OE\_OutputCurrent'}, ...
      varargin{:} );
