function pfocalbsbhs(varargin);
% pfocalbsbhs( [...] );
% Bay Stale Bay Heat Stale
h = timeplot({'Bay_Heat_Stale'}, ...
      'Bay Stale Bay Heat Stale', ...
      'Bay Heat Stale', ...
      {'Bay\_Heat\_Stale'}, ...
      varargin{:} );
