function pfocalgdsgdscs(varargin);
% pfocalgdsgdscs( [...] );
% GDS Cmd Status
h = ne_dstat({
  'GDS_Cal_Hi', 'GDS_cmd_stat', 0; ...
	'GDS_Cal_Lo', 'GDS_cmd_stat', 1; ...
	'GDS_Cal_Ref', 'GDS_cmd_stat', 2; ...
	'GDS_CO2_Ref', 'GDS_cmd_stat', 3; ...
	'GDS_MM_Pump', 'GDS_cmd_stat', 4; ...
	'GDS_MM_Exh', 'GDS_cmd_stat', 5; ...
	'GDS_CO2_Pump', 'GDS_cmd_stat', 6; ...
	'GDS_CO2_Exh', 'GDS_cmd_stat', 7 }, 'Cmd Status', varargin{:} );
