function pfocalmecofgc(varargin);
% pfocalmecofgc( [...] );
% ME CO2 Fwd Gas Current
h = timeplot({'Fwd_Gas_OutputCurrent'}, ...
      'ME CO2 Fwd Gas Current', ...
      'Current', ...
      {'Fwd\_Gas\_OutputCurrent'}, ...
      varargin{:} );
