function pfocalqclisspcnsr(varargin);
% pfocalqclisspcnsr( [...] );
% QCLISSP C NSR
h = timeplot({'SSP_C_noise_pct0','SSP_C_noise_pct1'}, ...
      'QCLISSP C NSR', ...
      'NSR', ...
      {'SSP\_C\_noise\_pct0','SSP\_C\_noise\_pct1'}, ...
      varargin{:} );
