function pfocalhkmebscooes(varargin);
% pfocalhkmebscooes( [...] );
% ME Bay Stale CO2 OE Stale
h = timeplot({'CO2_OE_Stale'}, ...
      'ME Bay Stale CO2 OE Stale', ...
      'CO2 OE Stale', ...
      {'CO2\_OE\_Stale'}, ...
      varargin{:} );
