function pfocalcocooec(varargin);
% pfocalcocooec( [...] );
% CO2 CO2 OE Current
h = timeplot({'CO2_OE_OutputCurrent'}, ...
      'CO2 CO2 OE Current', ...
      'Current', ...
      {'CO2\_OE\_OutputCurrent'}, ...
      varargin{:} );
