function pfocalmecocooes(varargin);
% pfocalmecocooes( [...] );
% ME CO2 CO2 OE Status
h = timeplot({'CO2_OE_DevStatus'}, ...
      'ME CO2 CO2 OE Status', ...
      'Status', ...
      {'CO2\_OE\_DevStatus'}, ...
      varargin{:} );
