function pfocalgpsgpddds(varargin);
% pfocalgpsgpddds( [...] );
% GPD DD Secs
h = timeplot({'GPS_secs_UTC'}, ...
      'GPD DD Secs', ...
      'Secs', ...
      {'GPS\_secs\_UTC'}, ...
      varargin{:} );
