function pfocalqclisspma(varargin);
% pfocalqclisspma( [...] );
% SSP M Amp
h = timeplot({'SSP_M_amp0','SSP_M_amp1','SSP_M_noise0','SSP_M_noise1'}, ...
      'SSP M Amp', ...
      'Amp', ...
      {'SSP\_M\_amp0','SSP\_M\_amp1','SSP\_M\_noise0','SSP\_M\_noise1'}, ...
      varargin{:} );
