function pfocalcoedcoehkouv(varargin);
% pfocalcoedcoehkouv( [...] );
% uD COE HK OUV
h = ne_dstat({
  'OUV0_CO2', 'uD_COE_stat0', 0; ...
	'OUV1_CO2', 'uD_COE_stat1', 0; ...
	'OUV2_CO2', 'uD_COE_stat2', 0; ...
	'OUV3_CO2', 'uD_COE_stat3', 0; ...
	'OUV4_CO2', 'uD_COE_stat4', 0; ...
	'OUV5_CO2', 'uD_COE_stat5', 0; ...
	'OUV6_CO2', 'uD_COE_stat6', 0; ...
	'OUV7_CO2', 'uD_COE_stat7', 0 }, 'OUV', varargin{:} );
