function pfocalqcliqclimo(varargin);
% pfocalqcliqclimo( [...] );
% QCLI M Overflow
h = ne_dstat({
  'CAOVF1_M', 'SSP_M_Flags', 0; ...
	'CAOVF2_M', 'SSP_M_Flags', 1; ...
	'CAOVF3_M', 'SSP_M_Flags', 2; ...
	'PAOVF1_M', 'SSP_M_Flags', 3; ...
	'PAOVF2_M', 'SSP_M_Flags', 4; ...
	'PAOVF3_M', 'SSP_M_Flags', 5; ...
	'ADOVF1_M', 'SSP_M_Flags', 6; ...
	'ADOVF2_M', 'SSP_M_Flags', 7; ...
	'ADOVF3_M', 'SSP_M_Flags', 8 }, 'Overflow', varargin{:} );
