function pfocalchchrt(varargin);
% pfocalchchrt( [...] );
% CH4 Rov T
h = timeplot({'CH4_Rov1T','CH4_Rov2T'}, ...
      'CH4 Rov T', ...
      'Rov T', ...
      {'CH4\_Rov1T','CH4\_Rov2T'}, ...
      varargin{:} );
