function pfocalqcliqclicssp(varargin);
% pfocalqcliqclicssp( [...] );
% QCLIQCLI C SSP
h = timeplot({'SSP_C_Status'}, ...
      'QCLIQCLI C SSP', ...
      'SSP', ...
      {'SSP\_C\_Status'}, ...
      varargin{:} );
