function pfocalcodcohke(varargin);
% pfocalcodcohke( [...] );
% uDCO2 HK Errs
h = timeplot({'uDCO2_errs'}, ...
      'uDCO2 HK Errs', ...
      'Errs', ...
      {'uDCO2\_errs'}, ...
      varargin{:} );
