function pfocalhkmebchoes(varargin);
% pfocalhkmebchoes( [...] );
% ME Bay CH4 OE Status
h = timeplot({'CH4_OE_DevStatus'}, ...
      'ME Bay CH4 OE Status', ...
      'Status', ...
      {'CH4\_OE\_DevStatus'}, ...
      varargin{:} );
