function pfocalhkgdslm(varargin);
% pfocalhkgdslm( [...] );
% GD slm
h = timeplot({'Cal_MassFlow','Cal_Set'}, ...
      'GD slm', ...
      'slm', ...
      {'Cal\_MassFlow','Cal\_Set'}, ...
      varargin{:} );
