function pfocalhkmebebhe(varargin);
% pfocalhkmebebhe( [...] );
% ME Bay Errors Bay Heat Errors
h = timeplot({'Bay_Heat_ErrorNumber','Bay_Heat_ErrorInstance','Bay_Heat_ErrorParameter'}, ...
      'ME Bay Errors Bay Heat Errors', ...
      'Bay Heat Errors', ...
      {'Bay\_Heat\_ErrorNumber','Bay\_Heat\_ErrorInstance','Bay\_Heat\_ErrorParameter'}, ...
      varargin{:} );
