function pfocalmecocooev(varargin);
% pfocalmecocooev( [...] );
% ME CO2 CO2 OE Voltage
h = timeplot({'CO2_OE_OutputVoltage'}, ...
      'ME CO2 CO2 OE Voltage', ...
      'Voltage', ...
      {'CO2\_OE\_OutputVoltage'}, ...
      varargin{:} );
