function pfocalqcliqcli_c_staterr(varargin);
% pfocalqcliqcli_c_staterr( [...] );
% QCLIQCLI C stat err
h = timeplot({'QCLI_C_err'}, ...
      'QCLIQCLI C stat err', ...
      'err', ...
      {'QCLI\_C\_err'}, ...
      varargin{:} );
