function pfocalmecoscooes(varargin);
% pfocalmecoscooes( [...] );
% ME CO2 Stale CO2 OE Stale
h = timeplot({'CO2_OE_Stale'}, ...
      'ME CO2 Stale CO2 OE Stale', ...
      'CO2 OE Stale', ...
      {'CO2\_OE\_Stale'}, ...
      varargin{:} );
