function pfocalcoedcoeptrht(varargin);
% pfocalcoedcoeptrht( [...] );
% uD COE PTRH T
h = timeplot({'uD_COE_OE_T','uD_COE_LH_T'}, ...
      'uD COE PTRH T', ...
      'T', ...
      {'uD\_COE\_OE\_T','uD\_COE\_LH\_T'}, ...
      varargin{:} );
