function pfocalchdchais(varargin);
% pfocalchdchais( [...] );
% uDCH4 AI Stat
h = timeplot({'uDCH4_stat'}, ...
      'uDCH4 AI Stat', ...
      'AI Stat', ...
      {'uDCH4\_stat'}, ...
      varargin{:} );
