function pfocalmoemoehkaiic(varargin);
% pfocalmoemoehkaiic( [...] );
% MOE HK AI I2C
h = timeplot({'GDS_MOE_I2C_Status'}, ...
      'MOE HK AI I2C', ...
      'AI I2C', ...
      {'GDS\_MOE\_I2C\_Status'}, ...
      varargin{:} );
