function pfocalqclisspcnsr(varargin);
% pfocalqclisspcnsr( [...] );
% SSP C NSR
h = timeplot({'SSP_C_noise_pct0','SSP_C_noise_pct1'}, ...
      'SSP C NSR', ...
      'NSR', ...
      {'SSP\_C\_noise\_pct0','SSP\_C\_noise\_pct1'}, ...
      varargin{:} );
