function pfocalmecoecooee(varargin);
% pfocalmecoecooee( [...] );
% ME CO2 Errors CO2 OE Errors
h = timeplot({'CO2_OE_ErrorNumber','CO2_OE_ErrorInstance','CO2_OE_ErrorParameter'}, ...
      'ME CO2 Errors CO2 OE Errors', ...
      'CO2 OE Errors', ...
      {'CO2\_OE\_ErrorNumber','CO2\_OE\_ErrorInstance','CO2\_OE\_ErrorParameter'}, ...
      varargin{:} );
