function pfocaldacsdcohkms(varargin);
% pfocaldacsdcohkms( [...] );
% uDAC Su DCO2 HK M Sat
h = ne_dstat({
  'MSat0', 'uDCO2_stat0', 2; ...
	'MSat1', 'uDCO2_stat1', 2; ...
	'MSat2', 'uDCO2_stat2', 2; ...
	'MSat3', 'uDCO2_stat3', 2; ...
	'MSat4', 'uDCO2_stat4', 2; ...
	'MSat5', 'uDCO2_stat5', 2; ...
	'MSat6', 'uDCO2_stat6', 2; ...
	'MSat7', 'uDCO2_stat7', 2 }, 'M Sat', varargin{:} );
