function pfocalcpchkstale(varargin);
% pfocalcpchkstale( [...] );
% CPC HK Stale
h = timeplot({'C_AbsP_Stale','C_DiffP_Stale','CPC_Stale'}, ...
      'CPC HK Stale', ...
      'Stale', ...
      {'C\_AbsP\_Stale','C\_DiffP\_Stale','CPC\_Stale'}, ...
      varargin{:} );
