function pfocalmoedmoeptrhrh(varargin);
% pfocalmoedmoeptrhrh( [...] );
% uD MOE PTRH RH
h = timeplot({'uD_MOE_OE_RH','uD_MOE_LH_RH'}, ...
      'uD MOE PTRH RH', ...
      'RH', ...
      {'uD\_MOE\_OE\_RH','uD\_MOE\_LH\_RH'}, ...
      varargin{:} );
