function pfocalbbhkics(varargin);
% pfocalbbhkics( [...] );
% Bay HK I2C Status
h = ne_dstat({
  'B_Pkg_coll', 'GDS_Bay_I2C_Status', 0; ...
	'B_Busy', 'GDS_Bay_I2C_Status', 1; ...
	'B_Bus', 'GDS_Bay_I2C_Status', 2; ...
	'B_Bad_addr', 'GDS_Bay_I2C_Status', 3; ...
	'B_Arb_lost', 'GDS_Bay_I2C_Status', 4; ...
	'B_Nack', 'GDS_Bay_I2C_Status', 5 }, 'I2C Status', varargin{:} );
