function pfocalchdchptrhrh(varargin);
% pfocalchdchptrhrh( [...] );
% uDCH4 PTRH RH
h = timeplot({'uDCH4_OE_RH','uDCH4_LH_RH'}, ...
      'uDCH4 PTRH RH', ...
      'RH', ...
      {'uDCH4\_OE\_RH','uDCH4\_LH\_RH'}, ...
      varargin{:} );
