function pfocalqcliqcli_c_statmode(varargin);
% pfocalqcliqcli_c_statmode( [...] );
% QCLIQCLI C stat mode
h = timeplot({'QCLI_C_mode'}, ...
      'QCLIQCLI C stat mode', ...
      'mode', ...
      {'QCLI\_C\_mode'}, ...
      varargin{:} );
