function pfocalhkmechchqclc(varargin);
% pfocalhkmechchqclc( [...] );
% ME CH4 CH4 QCL Current
h = timeplot({'CH4_QCL_OutputCurrent'}, ...
      'ME CH4 CH4 QCL Current', ...
      'Current', ...
      {'CH4\_QCL\_OutputCurrent'}, ...
      varargin{:} );
