function pfocalhkmechschqcls(varargin);
% pfocalhkmechschqcls( [...] );
% ME CH4 Stale CH4 QCL Stale
h = timeplot({'CH4_QCL_Stale'}, ...
      'ME CH4 Stale CH4 QCL Stale', ...
      'CH4 QCL Stale', ...
      {'CH4\_QCL\_Stale'}, ...
      varargin{:} );
