function pfocalqclisspca(varargin);
% pfocalqclisspca( [...] );
% QCLISSP C Amp
h = timeplot({'SSP_C_amp0','SSP_C_amp1','SSP_C_noise0','SSP_C_noise1'}, ...
      'QCLISSP C Amp', ...
      'Amp', ...
      {'SSP\_C\_amp0','SSP\_C\_amp1','SSP\_C\_noise0','SSP\_C\_noise1'}, ...
      varargin{:} );
