function pfocalchschoes(varargin);
% pfocalchschoes( [...] );
% CH4 Stale CH4 OE Stale
h = timeplot({'CH4_OE_Stale'}, ...
      'CH4 Stale CH4 OE Stale', ...
      'CH4 OE Stale', ...
      {'CH4\_OE\_Stale'}, ...
      varargin{:} );
