function pfocalhkmebbhs(varargin);
% pfocalhkmebbhs( [...] );
% ME Bay Bay Heat Status
h = timeplot({'Bay_Heat_DevStatus'}, ...
      'ME Bay Bay Heat Status', ...
      'Status', ...
      {'Bay\_Heat\_DevStatus'}, ...
      varargin{:} );
