function pfocalchsmes(varargin);
% pfocalchsmes( [...] );
% CH4 Stale ME Stale
h = timeplot({'CH4_Stale'}, ...
      'CH4 Stale ME Stale', ...
      'ME Stale', ...
      {'CH4\_Stale'}, ...
      varargin{:} );
