function pfocalmebfgs(varargin);
% pfocalmebfgs( [...] );
% ME Bay Fwd Gas Status
h = timeplot({'Fwd_Gas_DevStatus'}, ...
      'ME Bay Fwd Gas Status', ...
      'Status', ...
      {'Fwd\_Gas\_DevStatus'}, ...
      varargin{:} );
