function pfocalhkmebschoes(varargin);
% pfocalhkmebschoes( [...] );
% ME Bay Stale CH4 OE Stale
h = timeplot({'CH4_OE_Stale'}, ...
      'ME Bay Stale CH4 OE Stale', ...
      'CH4 OE Stale', ...
      {'CH4\_OE\_Stale'}, ...
      varargin{:} );
