function pfocaldacsdcohkfs(varargin);
% pfocaldacsdcohkfs( [...] );
% uDCO2 HK F Sat
h = ne_dstat({
  'FSat0', 'uDCO2_stat0', 1; ...
	'FSat1', 'uDCO2_stat1', 1; ...
	'FSat2', 'uDCO2_stat2', 1; ...
	'FSat3', 'uDCO2_stat3', 1; ...
	'FSat4', 'uDCO2_stat4', 1; ...
	'FSat5', 'uDCO2_stat5', 1; ...
	'FSat6', 'uDCO2_stat6', 1; ...
	'FSat7', 'uDCO2_stat7', 1 }, 'F Sat', varargin{:} );
