function pfocalqcli_qcli_m_statfifodep(varargin);
% pfocalqcli_qcli_m_statfifodep( [...] );
% QCLI M stat fifodep
h = timeplot({'QCLI_M_fifodep'}, ...
      'QCLI M stat fifodep', ...
      'fifodep', ...
      {'QCLI\_M\_fifodep'}, ...
      varargin{:} );
