function pfocalmebbhv(varargin);
% pfocalmebbhv( [...] );
% ME Bay Bay Heat Voltage
h = timeplot({'Bay_Heat_OutputVoltage'}, ...
      'ME Bay Bay Heat Voltage', ...
      'Voltage', ...
      {'Bay\_Heat\_OutputVoltage'}, ...
      varargin{:} );
