function pfocalchdchdac(varargin);
% pfocalchdchdac( [...] );
% uDCH4 DAC
h = timeplot({'uDCH4_VSet0','uDCH4_VSet1','uDCH4_VSet2','uDCH4_VSet3'}, ...
      'uDCH4 DAC', ...
      'DAC', ...
      {'uDCH4\_VSet0','uDCH4\_VSet1','uDCH4\_VSet2','uDCH4\_VSet3'}, ...
      varargin{:} );
