function pfocalwgpsgpshknnrmc(varargin);
% pfocalwgpsgpshknnrmc( [...] );
% GPS HK N N RMC
h = timeplot({'GPS_N_RMC'}, ...
      'GPS HK N N RMC', ...
      'N RMC', ...
      {'GPS\_N\_RMC'}, ...
      varargin{:} );
