function pfocalwgpsgpshkhdop(varargin);
% pfocalwgpsgpshkhdop( [...] );
% GPS HK HDOP
h = timeplot({'GPS_HDOP'}, ...
      'GPS HK HDOP', ...
      'HDOP', ...
      {'GPS\_HDOP'}, ...
      varargin{:} );
