function pfocalcocoqclc(varargin);
% pfocalcocoqclc( [...] );
% CO2 CO2 QCL Current
h = timeplot({'CO2_QCL_OutputCurrent'}, ...
      'CO2 CO2 QCL Current', ...
      'Current', ...
      {'CO2\_QCL\_OutputCurrent'}, ...
      varargin{:} );
