function pfocalmebbhc(varargin);
% pfocalmebbhc( [...] );
% ME Bay Bay Heat Current
h = timeplot({'Bay_Heat_OutputCurrent'}, ...
      'ME Bay Bay Heat Current', ...
      'Current', ...
      {'Bay\_Heat\_OutputCurrent'}, ...
      varargin{:} );
