function pfocalqcli_qcli_c_statskip(varargin);
% pfocalqcli_qcli_c_statskip( [...] );
% QCLI C stat Skip
h = timeplot({'SSP_C_TS'}, ...
      'QCLI C stat Skip', ...
      'Skip', ...
      {'SSP\_C\_TS'}, ...
      varargin{:} );
