function pfocaldacsdchais(varargin);
% pfocaldacsdchais( [...] );
% uDCH4 AI Stat
h = timeplot({'uDCH4_stat','uDCH4_stat'}, ...
      'uDCH4 AI Stat', ...
      'AI Stat', ...
      {'uDCH4\_stat','uDCH4\_stat'}, ...
      varargin{:} );
