function pfocalcofgv(varargin);
% pfocalcofgv( [...] );
% CO2 Fwd Gas Voltage
h = timeplot({'Fwd_Gas_OutputVoltage'}, ...
      'CO2 Fwd Gas Voltage', ...
      'Voltage', ...
      {'Fwd\_Gas\_OutputVoltage'}, ...
      varargin{:} );
