function pfocalcoedcoedac(varargin);
% pfocalcoedcoedac( [...] );
% uD COE DAC
h = timeplot({'uD_COE_VSet0','uD_COE_VSet1','uD_COE_VSet2','uD_COE_VSet3'}, ...
      'uD COE DAC', ...
      'DAC', ...
      {'uD\_COE\_VSet0','uD\_COE\_VSet1','uD\_COE\_VSet2','uD\_COE\_VSet3'}, ...
      varargin{:} );
