function pfocalcoecoft(varargin);
% pfocalcoecoft( [...] );
% CO2 Flow T
h = timeplot({'CO2_SamInT','CO2_SamOutT'}, ...
      'CO2 Flow T', ...
      'Flow T', ...
      {'CO2\_SamInT','CO2\_SamOutT'}, ...
      varargin{:} );
