function pfocaldacsdchhke(varargin);
% pfocaldacsdchhke( [...] );
% uDCH4 HK Errs
h = timeplot({'uDCH4_errs','uDCH4_errs'}, ...
      'uDCH4 HK Errs', ...
      'Errs', ...
      {'uDCH4\_errs','uDCH4\_errs'}, ...
      varargin{:} );
