function pfocalwwhkn_errors(varargin);
% pfocalwwhkn_errors( [...] );
% Wind HK N errors
h = timeplot({'Wind_N_errors'}, ...
      'Wind HK N errors', ...
      'N errors', ...
      {'Wind\_N\_errors'}, ...
      varargin{:} );
