function pfocalmoemoehkn(varargin);
% pfocalmoemoehkn( [...] );
% MOE HK Nreads
h = timeplot({'GDS_MOE_Nreads'}, ...
      'MOE HK Nreads', ...
      'Nreads', ...
      {'GDS\_MOE\_Nreads'}, ...
      varargin{:} );
