function pfocalgdnccm(varargin);
% pfocalgdnccm( [...] );
% GD nccm
h = timeplot({'Cal_MassFlow','Cal_Set'}, ...
      'GD nccm', ...
      'nccm', ...
      {'Cal\_MassFlow','Cal\_Set'}, ...
      varargin{:} );
