function pfocalqcliqclimssp(varargin);
% pfocalqcliqclimssp( [...] );
% QCLI M SSP
h = timeplot({'SSP_M_Status'}, ...
      'QCLI M SSP', ...
      'SSP', ...
      {'SSP\_M\_Status'}, ...
      varargin{:} );
