function pfocalwgpswt(varargin);
% pfocalwgpswt( [...] );
% Wind Temp
h = timeplot({'Wind_SonicTemp'}, ...
      'Wind Temp', ...
      'Temp', ...
      {'Wind\_SonicTemp'}, ...
      varargin{:} );
