function pfocalcoecoct(varargin);
% pfocalcoecoct( [...] );
% CO2 Cell T
h = timeplot({'CO2_Cell1T','CO2_Cell2T','CO2_Cell3T'}, ...
      'CO2 Cell T', ...
      'Cell T', ...
      {'CO2\_Cell1T','CO2\_Cell2T','CO2\_Cell3T'}, ...
      varargin{:} );
