function pfocalqclitsspm(varargin);
% pfocalqclitsspm( [...] );
% Temps SSP M
h = timeplot({'SSP_M_T_FPGA','SSP_M_T_HtSink'}, ...
      'Temps SSP M', ...
      'SSP M', ...
      {'SSP\_M\_T\_FPGA','SSP\_M\_T\_HtSink'}, ...
      varargin{:} );
