function pfocalhkmecocoqclv(varargin);
% pfocalhkmecocoqclv( [...] );
% ME CO2 CO2 QCL Voltage
h = timeplot({'CO2_QCL_OutputVoltage'}, ...
      'ME CO2 CO2 QCL Voltage', ...
      'Voltage', ...
      {'CO2\_QCL\_OutputVoltage'}, ...
      varargin{:} );
