function pfocalhkmebcooec(varargin);
% pfocalhkmebcooec( [...] );
% ME Bay CO2 OE Current
h = timeplot({'CO2_OE_OutputCurrent'}, ...
      'ME Bay CO2 OE Current', ...
      'Current', ...
      {'CO2\_OE\_OutputCurrent'}, ...
      varargin{:} );
