function pfocalcodcoptrhrh(varargin);
% pfocalcodcoptrhrh( [...] );
% uDCO2 PTRH RH
h = timeplot({'uDCO2_OE_RH','uDCO2_LH_RH'}, ...
      'uDCO2 PTRH RH', ...
      'RH', ...
      {'uDCO2\_OE\_RH','uDCO2\_LH\_RH'}, ...
      varargin{:} );
