function pfocalcofgs(varargin);
% pfocalcofgs( [...] );
% CO2 Fwd Gas Status
h = timeplot({'Fwd_Gas_DevStatus'}, ...
      'CO2 Fwd Gas Status', ...
      'Status', ...
      {'Fwd\_Gas\_DevStatus'}, ...
      varargin{:} );
