function pfocalchdchhkain(varargin);
% pfocalchdchhkain( [...] );
% uDCH4 HK AI N
h = timeplot({'uDCH4_N'}, ...
      'uDCH4 HK AI N', ...
      'AI N', ...
      {'uDCH4\_N'}, ...
      varargin{:} );
