function pfocalbbhv(varargin);
% pfocalbbhv( [...] );
% Bay Bay Heat Voltage
h = timeplot({'Bay_Heat_OutputVoltage'}, ...
      'Bay Bay Heat Voltage', ...
      'Voltage', ...
      {'Bay\_Heat\_OutputVoltage'}, ...
      varargin{:} );
