function pfocalgdsgdshkn(varargin);
% pfocalgdsgdshkn( [...] );
% GDS HK Nreads
h = timeplot({'GDS_Nreads'}, ...
      'GDS HK Nreads', ...
      'Nreads', ...
      {'GDS\_Nreads'}, ...
      varargin{:} );
