function pfocalmechechoee(varargin);
% pfocalmechechoee( [...] );
% ME CH4 Errors CH4 OE Errors
h = timeplot({'CH4_OE_ErrorNumber','CH4_OE_ErrorInstance','CH4_OE_ErrorParameter'}, ...
      'ME CH4 Errors CH4 OE Errors', ...
      'CH4 OE Errors', ...
      {'CH4\_OE\_ErrorNumber','CH4\_OE\_ErrorInstance','CH4\_OE\_ErrorParameter'}, ...
      varargin{:} );
