function pfocalmecosmes(varargin);
% pfocalmecosmes( [...] );
% ME CO2 Stale ME Stale
h = timeplot({'ME_CO2_Stale'}, ...
      'ME CO2 Stale ME Stale', ...
      'ME Stale', ...
      {'ME\_CO2\_Stale'}, ...
      varargin{:} );
