function pfocaldacsdcodac(varargin);
% pfocaldacsdcodac( [...] );
% uDCO2 DAC
h = timeplot({'uDCO2_VSet0','uDCO2_VSet1','uDCO2_VSet2','uDCO2_VSet3'}, ...
      'uDCO2 DAC', ...
      'DAC', ...
      {'uDCO2\_VSet0','uDCO2\_VSet1','uDCO2\_VSet2','uDCO2\_VSet3'}, ...
      varargin{:} );
