function pfocalmoedmoehkain(varargin);
% pfocalmoedmoehkain( [...] );
% uD MOE HK AI N
h = timeplot({'uD_MOE_N'}, ...
      'uD MOE HK AI N', ...
      'AI N', ...
      {'uD\_MOE\_N'}, ...
      varargin{:} );
