function pfocalqcliqcli_c_statflash(varargin);
% pfocalqcliqcli_c_statflash( [...] );
% QCLIQCLI C stat flash
h = timeplot({'QCLI_C_flash'}, ...
      'QCLIQCLI C stat flash', ...
      'flash', ...
      {'QCLI\_C\_flash'}, ...
      varargin{:} );
