function pfocalqcli_qcli_m_statmode(varargin);
% pfocalqcli_qcli_m_statmode( [...] );
% QCLI M stat mode
h = timeplot({'QCLI_M_mode'}, ...
      'QCLI M stat mode', ...
      'mode', ...
      {'QCLI\_M\_mode'}, ...
      varargin{:} );
