function pfocalwgpsgpshknn_errors(varargin);
% pfocalwgpsgpshknn_errors( [...] );
% GPS HK N N errors
h = timeplot({'GPS_N_errors'}, ...
      'GPS HK N N errors', ...
      'N errors', ...
      {'GPS\_N\_errors'}, ...
      varargin{:} );
