function pfocaldacsdcohke(varargin);
% pfocaldacsdcohke( [...] );
% uDAC Su DCO2 HK Errs
h = timeplot({'uDCO2_errs'}, ...
      'uDAC Su DCO2 HK Errs', ...
      'Errs', ...
      {'uDCO2\_errs'}, ...
      varargin{:} );
