function pfocalchdchptrhp(varargin);
% pfocalchdchptrhp( [...] );
% uDCH4 PTRH P
h = timeplot({'uDCH4_OE_P','uDCH4_LH_P'}, ...
      'uDCH4 PTRH P', ...
      'P', ...
      {'uDCH4\_OE\_P','uDCH4\_LH\_P'}, ...
      varargin{:} );
