function pfocalwww(varargin);
% pfocalwww( [...] );
% Wind Wind
h = timeplot({'Wind_U','Wind_V','Wind_W'}, ...
      'Wind Wind', ...
      'Wind', ...
      {'Wind\_U','Wind\_V','Wind\_W'}, ...
      varargin{:} );
