function pfocalcoscoqcls(varargin);
% pfocalcoscoqcls( [...] );
% CO2 Stale CO2 QCL Stale
h = timeplot({'CO2_QCL_Stale'}, ...
      'CO2 Stale CO2 QCL Stale', ...
      'CO2 QCL Stale', ...
      {'CO2\_QCL\_Stale'}, ...
      varargin{:} );
