function pfocalcodcoptrht(varargin);
% pfocalcodcoptrht( [...] );
% uDCO2 PTRH T
h = timeplot({'uDCO2_OE_T','uDCO2_LH_T'}, ...
      'uDCO2 PTRH T', ...
      'T', ...
      {'uDCO2\_OE\_T','uDCO2\_LH\_T'}, ...
      varargin{:} );
