function pfocalhkcpct(varargin);
% pfocalhkcpct( [...] );
% CPC Torr
h = timeplot({'C_AbsP_Set','C_DiffP_Set'}, ...
      'CPC Torr', ...
      'Torr', ...
      {'C\_AbsP\_Set','C\_DiffP\_Set'}, ...
      varargin{:} );
