function pfocalqcliqcli_c_statfifodep(varargin);
% pfocalqcliqcli_c_statfifodep( [...] );
% QCLIQCLI C stat fifodep
h = timeplot({'QCLI_C_fifodep'}, ...
      'QCLIQCLI C stat fifodep', ...
      'fifodep', ...
      {'QCLI\_C\_fifodep'}, ...
      varargin{:} );
