function pfocalwgpsgpshkstale(varargin);
% pfocalwgpsgpshkstale( [...] );
% GPS HK Stale
h = timeplot({'GPS_stale'}, ...
      'GPS HK Stale', ...
      'Stale', ...
      {'GPS\_stale'}, ...
      varargin{:} );
