function pfocalchchqclc(varargin);
% pfocalchchqclc( [...] );
% CH4 CH4 QCL Current
h = timeplot({'CH4_QCL_OutputCurrent'}, ...
      'CH4 CH4 QCL Current', ...
      'Current', ...
      {'CH4\_QCL\_OutputCurrent'}, ...
      varargin{:} );
