function pfocalmebcooes(varargin);
% pfocalmebcooes( [...] );
% ME Bay CO2 OE Status
h = timeplot({'CO2_OE_DevStatus'}, ...
      'ME Bay CO2 OE Status', ...
      'Status', ...
      {'CO2\_OE\_DevStatus'}, ...
      varargin{:} );
