function pfocalmoedmoeptrhp(varargin);
% pfocalmoedmoeptrhp( [...] );
% uD MOE PTRH P
h = timeplot({'uD_MOE_OE_P','uD_MOE_LH_P'}, ...
      'uD MOE PTRH P', ...
      'P', ...
      {'uD\_MOE\_OE\_P','uD\_MOE\_LH\_P'}, ...
      varargin{:} );
