function pfocalcoedcoeais(varargin);
% pfocalcoedcoeais( [...] );
% uD COE AI Stat
h = timeplot({'uD_COE_stat'}, ...
      'uD COE AI Stat', ...
      'AI Stat', ...
      {'uD\_COE\_stat'}, ...
      varargin{:} );
