function pfocalqcli_qcli_c_statrw(varargin);
% pfocalqcli_qcli_c_statrw( [...] );
% QCLI C stat rw
h = timeplot({'QCLI_C_rw'}, ...
      'QCLI C stat rw', ...
      'rw', ...
      {'QCLI\_C\_rw'}, ...
      varargin{:} );
