function pfocalwgpsgpsc(varargin);
% pfocalwgpsgpsc( [...] );
% GPS Course
h = timeplot({'GPS_Course'}, ...
      'GPS Course', ...
      'Course', ...
      {'GPS\_Course'}, ...
      varargin{:} );
