function pfocalhks(varargin);
% pfocalhks( [...] );
% HK Status
h = ne_dstat({
  'BAT_Pwr_DS', 'DS84A', 4; ...
	'BAT_Purge_DS', 'DS848', 5; ...
	'QCLI_C_Reset_DS', 'DS84C', 1; ...
	'QCLI_M_Reset_DS', 'DS868', 1; ...
	'BAT_Pwr_S', 'DS873', 4; ...
	'SW0', 'IOSwS', 0; ...
	'SW1', 'IOSwS', 1; ...
	'FltMd', 'IOSwS', 2 }, 'Status', varargin{:} );
