function pfocalqcliqcli_c_statsn(varargin);
% pfocalqcliqcli_c_statsn( [...] );
% QCLIQCLI C stat SN
h = timeplot({'SSP_C_SN'}, ...
      'QCLIQCLI C stat SN', ...
      'SN', ...
      {'SSP\_C\_SN'}, ...
      varargin{:} );
