function pfocalmebsbhs(varargin);
% pfocalmebsbhs( [...] );
% ME Bay Stale Bay Heat Stale
h = timeplot({'Bay_Heat_Stale'}, ...
      'ME Bay Stale Bay Heat Stale', ...
      'Bay Heat Stale', ...
      {'Bay\_Heat\_Stale'}, ...
      varargin{:} );
