function pfocalbbli(varargin);
% pfocalbbli( [...] );
% Bay Laser I
h = timeplot({'CO2_QCL_I','CH4_QCL_I'}, ...
      'Bay Laser I', ...
      'Laser I', ...
      {'CO2\_QCL\_I','CH4\_QCL\_I'}, ...
      varargin{:} );
