function pfocalbbhkics(varargin);
% pfocalbbhkics( [...] );
% Bay HK I2C Status
h = timeplot({'GDS_Bay_I2C_Status'}, ...
      'Bay HK I2C Status', ...
      'I2C Status', ...
      {'GDS\_Bay\_I2C\_Status'}, ...
      varargin{:} );
