function pfocalgdhkstale(varargin);
% pfocalgdhkstale( [...] );
% GD HK Stale
h = timeplot({'Cal_Stale','GD_Stale'}, ...
      'GD HK Stale', ...
      'Stale', ...
      {'Cal\_Stale','GD\_Stale'}, ...
      varargin{:} );
