function pfocaldacsdcohkouv(varargin);
% pfocaldacsdcohkouv( [...] );
% uDAC Su DCO2 HK OUV
h = ne_dstat({
  'OUV0', 'uDCO2_stat0', 0; ...
	'OUV1', 'uDCO2_stat1', 0; ...
	'OUV2', 'uDCO2_stat2', 0; ...
	'OUV3', 'uDCO2_stat3', 0; ...
	'OUV4', 'uDCO2_stat4', 0; ...
	'OUV5', 'uDCO2_stat5', 0; ...
	'OUV6', 'uDCO2_stat6', 0; ...
	'OUV7', 'uDCO2_stat7', 0 }, 'OUV', varargin{:} );
