function pfocalmoedmoehke(varargin);
% pfocalmoedmoehke( [...] );
% uD MOE HK Errs
h = timeplot({'uD_MOE_errs'}, ...
      'uD MOE HK Errs', ...
      'Errs', ...
      {'uD\_MOE\_errs'}, ...
      varargin{:} );
