function pfocaldacsdchptrht(varargin);
% pfocaldacsdchptrht( [...] );
% uDCH4 PTRH T
h = timeplot({'uDCH4_OE_T','uDCH4_LH_T','uDCH4_OE_T','uDCH4_LH_T'}, ...
      'uDCH4 PTRH T', ...
      'T', ...
      {'uDCH4\_OE\_T','uDCH4\_LH\_T','uDCH4\_OE\_T','uDCH4\_LH\_T'}, ...
      varargin{:} );
