function pfocalmecocooec(varargin);
% pfocalmecocooec( [...] );
% ME CO2 CO2 OE Current
h = timeplot({'CO2_OE_OutputCurrent'}, ...
      'ME CO2 CO2 OE Current', ...
      'Current', ...
      {'CO2\_OE\_OutputCurrent'}, ...
      varargin{:} );
