function pfocalwgpsicmm(varargin);
% pfocalwgpsicmm( [...] );
% ICM Max
h = timeplot({'ICM_max_g','ICM_max_accel_x','ICM_max_accel_y','ICM_max_accel_z'}, ...
      'ICM Max', ...
      'Max', ...
      {'ICM\_max\_g','ICM\_max\_accel\_x','ICM\_max\_accel\_y','ICM\_max\_accel\_z'}, ...
      varargin{:} );
