function pfocalmechsmes(varargin);
% pfocalmechsmes( [...] );
% ME CH4 Stale ME Stale
h = timeplot({'ME_CH4_Stale'}, ...
      'ME CH4 Stale ME Stale', ...
      'ME Stale', ...
      {'ME\_CH4\_Stale'}, ...
      varargin{:} );
