function pfocalgpsgpsddd(varargin);
% pfocalgpsgpsddd( [...] );
% GPS DD Date
h = timeplot({'GPS_DD','GPS_MM','GPS_YY'}, ...
      'GPS DD Date', ...
      'Date', ...
      {'DD','MM','YY'}, ...
      varargin{:} );
