function pfocalwgpsicmhkmsecs(varargin);
% pfocalwgpsicmhkmsecs( [...] );
% ICM HK msecs
h = timeplot({'ICM_msecs'}, ...
      'ICM HK msecs', ...
      'msecs', ...
      {'ICM\_msecs'}, ...
      varargin{:} );
