function pfocalqclisspmnsr(varargin);
% pfocalqclisspmnsr( [...] );
% SSP M NSR
h = timeplot({'SSP_M_noise_pct0','SSP_M_noise_pct1'}, ...
      'SSP M NSR', ...
      'NSR', ...
      {'SSP\_M\_noise\_pct0','SSP\_M\_noise\_pct1'}, ...
      varargin{:} );
