function pfocalmecoefge(varargin);
% pfocalmecoefge( [...] );
% ME CO2 Errors Fwd Gas Errors
h = timeplot({'Fwd_Gas_ErrorNumber','Fwd_Gas_ErrorInstance','Fwd_Gas_ErrorParameter'}, ...
      'ME CO2 Errors Fwd Gas Errors', ...
      'Fwd Gas Errors', ...
      {'Fwd\_Gas\_ErrorNumber','Fwd\_Gas\_ErrorInstance','Fwd\_Gas\_ErrorParameter'}, ...
      varargin{:} );
