function pfocalqcli_qcli_m_statrw(varargin);
% pfocalqcli_qcli_m_statrw( [...] );
% QCLI M stat rw
h = timeplot({'QCLI_M_rw'}, ...
      'QCLI M stat rw', ...
      'rw', ...
      {'QCLI\_M\_rw'}, ...
      varargin{:} );
