function pfocalcoedcoeptrhrh(varargin);
% pfocalcoedcoeptrhrh( [...] );
% uD COE PTRH RH
h = timeplot({'uD_COE_OE_RH','uD_COE_LH_RH'}, ...
      'uD COE PTRH RH', ...
      'RH', ...
      {'uD\_COE\_OE\_RH','uD\_COE\_LH\_RH'}, ...
      varargin{:} );
