function pfocalbbhs(varargin);
% pfocalbbhs( [...] );
% Bay Bay Heat Status
h = timeplot({'Bay_Heat_DevStatus'}, ...
      'Bay Bay Heat Status', ...
      'Status', ...
      {'Bay\_Heat\_DevStatus'}, ...
      varargin{:} );
