function pfocaldacsdcoptp(varargin);
% pfocaldacsdcoptp( [...] );
% uDCO2 PT P
h = timeplot({'uDCO2_OE_P','uDCO2_LH_P'}, ...
      'uDCO2 PT P', ...
      'P', ...
      {'uDCO2\_OE\_P','uDCO2\_LH\_P'}, ...
      varargin{:} );
