function pfocalhkmecocoqcls(varargin);
% pfocalhkmecocoqcls( [...] );
% ME CO2 CO2 QCL Status
h = timeplot({'CO2_QCL_DevStatus'}, ...
      'ME CO2 CO2 QCL Status', ...
      'Status', ...
      {'CO2\_QCL\_DevStatus'}, ...
      varargin{:} );
