function pfocalqcli_qcli_m_stats(varargin);
% pfocalqcli_qcli_m_stats( [...] );
% QCLI M stat Stale
h = timeplot({'QCLI_M_Stale','SSP_M_Stale'}, ...
      'QCLI M stat Stale', ...
      'Stale', ...
      {'QCLI\_M\_Stale','SSP\_M\_Stale'}, ...
      varargin{:} );
