function pfocalcoecoehkics(varargin);
% pfocalcoecoehkics( [...] );
% COE HK I2C Status
h = ne_dstat({
  'C_Pkg_coll', 'GDS_COE_I2C_Status', 0; ...
	'C_Busy', 'GDS_COE_I2C_Status', 1; ...
	'C_Bus', 'GDS_COE_I2C_Status', 2; ...
	'C_Bad_addr', 'GDS_COE_I2C_Status', 3; ...
	'C_Arb_lost', 'GDS_COE_I2C_Status', 4; ...
	'C_Nack', 'GDS_COE_I2C_Status', 5 }, 'I2C Status', varargin{:} );
