function pfocalhkgdhks(varargin);
% pfocalhkgdhks( [...] );
% GD HK Status
h = timeplot({'Cal_Status'}, ...
      'GD HK Status', ...
      'Status', ...
      {'Cal\_Status'}, ...
      varargin{:} );
