function pfocaldacsdcoais(varargin);
% pfocaldacsdcoais( [...] );
% uDCO2 AI Stat
h = timeplot({'uDCO2_stat'}, ...
      'uDCO2 AI Stat', ...
      'AI Stat', ...
      {'uDCO2\_stat'}, ...
      varargin{:} );
