function pfocalqcliqclimw(varargin);
% pfocalqcliqclimw( [...] );
% QCLI M Wave
h = timeplot({'QCLI_M_Wave'}, ...
      'QCLI M Wave', ...
      'Wave', ...
      {'QCLI\_M\_Wave'}, ...
      varargin{:} );
