function pfocalmechchqcls(varargin);
% pfocalmechchqcls( [...] );
% ME CH4 CH4 QCL Status
h = timeplot({'CH4_QCL_DevStatus'}, ...
      'ME CH4 CH4 QCL Status', ...
      'Status', ...
      {'CH4\_QCL\_DevStatus'}, ...
      varargin{:} );
