function pfocalqcli_qcli_m_statskip(varargin);
% pfocalqcli_qcli_m_statskip( [...] );
% QCLI M stat Skip
h = timeplot({'SSP_M_TS'}, ...
      'QCLI M stat Skip', ...
      'Skip', ...
      {'SSP\_M\_TS'}, ...
      varargin{:} );
