function pfocalmoemoecp(varargin);
% pfocalmoemoecp( [...] );
% MOE Cell P
h = timeplot({'GDS_MOE_CellP_Hi'}, ...
      'MOE Cell P', ...
      'Cell P', ...
      {'GDS\_MOE\_CellP\_Hi'}, ...
      varargin{:} );
