function pfocalcocoecp(varargin);
% pfocalcocoecp( [...] );
% COE Cell P
h = timeplot({'GDS_COE_CellP_Hi'}, ...
      'COE Cell P', ...
      'Cell P', ...
      {'GDS\_COE\_CellP\_Hi'}, ...
      varargin{:} );
