function pfocalmoedmoeptrht(varargin);
% pfocalmoedmoeptrht( [...] );
% uD MOE PTRH T
h = timeplot({'uD_MOE_OE_T','uD_MOE_LH_T'}, ...
      'uD MOE PTRH T', ...
      'T', ...
      {'uD\_MOE\_OE\_T','uD\_MOE\_LH\_T'}, ...
      varargin{:} );
