function pfocalchchoes(varargin);
% pfocalchchoes( [...] );
% CH4 CH4 OE Status
h = timeplot({'CH4_OE_DevStatus'}, ...
      'CH4 CH4 OE Status', ...
      'Status', ...
      {'CH4\_OE\_DevStatus'}, ...
      varargin{:} );
