function pfocalhkmpchks(varargin);
% pfocalhkmpchks( [...] );
% MPC HK Status
h = timeplot({'M_AbsP_Status'}, ...
      'MPC HK Status', ...
      'Status', ...
      {'M\_AbsP\_Status'}, ...
      varargin{:} );
