function pfocalqcli_qcli_m_statsn(varargin);
% pfocalqcli_qcli_m_statsn( [...] );
% QCLI M stat SN
h = timeplot({'SSP_M_SN'}, ...
      'QCLI M stat SN', ...
      'SN', ...
      {'SSP\_M\_SN'}, ...
      varargin{:} );
