function pfocalqcliqclims(varargin);
% pfocalqcliqclims( [...] );
% QCLI M Scan
h = timeplot({'SSP_M_Num'}, ...
      'QCLI M Scan', ...
      'Scan', ...
      {'SSP\_M\_Num'}, ...
      varargin{:} );
