function pfocalcoedcoehke(varargin);
% pfocalcoedcoehke( [...] );
% uD COE HK Errs
h = timeplot({'uD_COE_errs'}, ...
      'uD COE HK Errs', ...
      'Errs', ...
      {'uD\_COE\_errs'}, ...
      varargin{:} );
