function pfocalmoedmoehkms(varargin);
% pfocalmoedmoehkms( [...] );
% uD MOE HK M Sat
h = ne_dstat({
  'MSat0_CH4', 'uD_MOE_stat0', 2; ...
	'MSat1_CH4', 'uD_MOE_stat1', 2; ...
	'MSat2_CH4', 'uD_MOE_stat2', 2; ...
	'MSat3_CH4', 'uD_MOE_stat3', 2; ...
	'MSat4_CH4', 'uD_MOE_stat4', 2; ...
	'MSat5_CH4', 'uD_MOE_stat5', 2; ...
	'MSat6_CH4', 'uD_MOE_stat6', 2; ...
	'MSat7_CH4', 'uD_MOE_stat7', 2 }, 'M Sat', varargin{:} );
