function pfocalmecosfgs(varargin);
% pfocalmecosfgs( [...] );
% ME CO2 Stale Fwd Gas Stale
h = timeplot({'Fwd_Gas_Stale'}, ...
      'ME CO2 Stale Fwd Gas Stale', ...
      'Fwd Gas Stale', ...
      {'Fwd\_Gas\_Stale'}, ...
      varargin{:} );
