function pfocalmecoscoqcls(varargin);
% pfocalmecoscoqcls( [...] );
% ME CO2 Stale CO2 QCL Stale
h = timeplot({'CO2_QCL_Stale'}, ...
      'ME CO2 Stale CO2 QCL Stale', ...
      'CO2 QCL Stale', ...
      {'CO2\_QCL\_Stale'}, ...
      varargin{:} );
