function pfocalwgpsgpshknn(varargin);
% pfocalwgpsgpshknn( [...] );
% GPS HK N N other
h = timeplot({'GPS_N_other'}, ...
      'GPS HK N N other', ...
      'N other', ...
      {'GPS\_N\_other'}, ...
      varargin{:} );
