function pfocalchchqclv(varargin);
% pfocalchchqclv( [...] );
% CH4 CH4 QCL Voltage
h = timeplot({'CH4_QCL_OutputVoltage'}, ...
      'CH4 CH4 QCL Voltage', ...
      'Voltage', ...
      {'CH4\_QCL\_OutputVoltage'}, ...
      varargin{:} );
