function pfocalqcliqclicw(varargin);
% pfocalqcliqclicw( [...] );
% QCLIQCLI C Wave
h = timeplot({'QCLI_C_Wave'}, ...
      'QCLIQCLI C Wave', ...
      'Wave', ...
      {'QCLI\_C\_Wave'}, ...
      varargin{:} );
