function pfocalwgpswhks(varargin);
% pfocalwgpswhks( [...] );
% Wind HK Stale
h = timeplot({'Wind_stale'}, ...
      'Wind HK Stale', ...
      'Stale', ...
      {'Wind\_stale'}, ...
      varargin{:} );
