function pfocalqcli_qcli_m_staterr(varargin);
% pfocalqcli_qcli_m_staterr( [...] );
% QCLI M stat err
h = timeplot({'QCLI_M_err'}, ...
      'QCLI M stat err', ...
      'err', ...
      {'QCLI\_M\_err'}, ...
      varargin{:} );
