function pfocalchchoet(varargin);
% pfocalchchoet( [...] );
% CH4 CH4 OE Temp
h = timeplot({'CH4_OE_T','CH4_OE_Set_T','CH4_OE_Sink_T'}, ...
      'CH4 CH4 OE Temp', ...
      'Temp', ...
      {'CH4\_OE\_T','CH4\_OE\_Set\_T','CH4\_OE\_Sink\_T'}, ...
      varargin{:} );
