function pfocalmechchoev(varargin);
% pfocalmechchoev( [...] );
% ME CH4 CH4 OE Voltage
h = timeplot({'CH4_OE_OutputVoltage'}, ...
      'ME CH4 CH4 OE Voltage', ...
      'Voltage', ...
      {'CH4\_OE\_OutputVoltage'}, ...
      varargin{:} );
