function pfocalhkmebsmes(varargin);
% pfocalhkmebsmes( [...] );
% ME Bay Stale ME Stale
h = timeplot({'ME_Bay_Stale'}, ...
      'ME Bay Stale ME Stale', ...
      'ME Stale', ...
      {'ME\_Bay\_Stale'}, ...
      varargin{:} );
