function pfocalgdsgdshkics(varargin);
% pfocalgdsgdshkics( [...] );
% GDS HK I2C Status
h = ne_dstat({
  'Pkg_coll', 'GDS_I2C_Status', 0; ...
	'Busy', 'GDS_I2C_Status', 1; ...
	'Bus', 'GDS_I2C_Status', 2; ...
	'Bad_addr', 'GDS_I2C_Status', 3; ...
	'Arb_lost', 'GDS_I2C_Status', 4; ...
	'Nack', 'GDS_I2C_Status', 5 }, 'I2C Status', varargin{:} );
