function pfocalqcliqcli_c_stats(varargin);
% pfocalqcliqcli_c_stats( [...] );
% QCLIQCLI C stat Stale
h = timeplot({'QCLI_C_Stale','SSP_C_Stale'}, ...
      'QCLIQCLI C stat Stale', ...
      'Stale', ...
      {'QCLI\_C\_Stale','SSP\_C\_Stale'}, ...
      varargin{:} );
