function pfocalqcliqcli_c_statskip(varargin);
% pfocalqcliqcli_c_statskip( [...] );
% QCLIQCLI C stat Skip
h = timeplot({'SSP_C_TS'}, ...
      'QCLIQCLI C stat Skip', ...
      'Skip', ...
      {'SSP\_C\_TS'}, ...
      varargin{:} );
