function pfocalmebsfgs(varargin);
% pfocalmebsfgs( [...] );
% ME Bay Stale Fwd Gas Stale
h = timeplot({'Fwd_Gas_Stale'}, ...
      'ME Bay Stale Fwd Gas Stale', ...
      'Fwd Gas Stale', ...
      {'Fwd\_Gas\_Stale'}, ...
      varargin{:} );
