function pfocalhktmtd(varargin);
% pfocalhktmtd( [...] );
% HKT Mbase T Drift
h = timeplot({'SysTDrift'}, ...
      'HKT Mbase T Drift', ...
      'T Drift', ...
      {'SysTDrift'}, ...
      varargin{:} );
