function pfocalmoedmoedac(varargin);
% pfocalmoedmoedac( [...] );
% uD MOE DAC
h = timeplot({'uD_MOE_VSet0','uD_MOE_VSet1','uD_MOE_VSet2','uD_MOE_VSet3'}, ...
      'uD MOE DAC', ...
      'DAC', ...
      {'uD\_MOE\_VSet0','uD\_MOE\_VSet1','uD\_MOE\_VSet2','uD\_MOE\_VSet3'}, ...
      varargin{:} );
