function pfocalqclitsspc(varargin);
% pfocalqclitsspc( [...] );
% QCLI Temps SSP C
h = timeplot({'SSP_C_T_FPGA','SSP_C_T_HtSink'}, ...
      'QCLI Temps SSP C', ...
      'SSP C', ...
      {'SSP\_C\_T\_FPGA','SSP\_C\_T\_HtSink'}, ...
      varargin{:} );
