function pfocalcocoqclv(varargin);
% pfocalcocoqclv( [...] );
% CO2 CO2 QCL Voltage
h = timeplot({'CO2_QCL_OutputVoltage'}, ...
      'CO2 CO2 QCL Voltage', ...
      'Voltage', ...
      {'CO2\_QCL\_OutputVoltage'}, ...
      varargin{:} );
