function pfocaldacsdcoais(varargin);
% pfocaldacsdcoais( [...] );
% uDAC Su DCO2 AI Stat
h = timeplot({'uDCO2_stat'}, ...
      'uDAC Su DCO2 AI Stat', ...
      'AI Stat', ...
      {'uDCO2\_stat'}, ...
      varargin{:} );
