function pfocalchschqcls(varargin);
% pfocalchschqcls( [...] );
% CH4 Stale CH4 QCL Stale
h = timeplot({'CH4_QCL_Stale'}, ...
      'CH4 Stale CH4 QCL Stale', ...
      'CH4 QCL Stale', ...
      {'CH4\_QCL\_Stale'}, ...
      varargin{:} );
