function pfocalqcli_c_staterr(varargin);
% pfocalqcli_c_staterr( [...] );
% QCLI C stat err
h = timeplot({'QCLI_C_err'}, ...
      'QCLI C stat err', ...
      'err', ...
      {'QCLI\_C\_err'}, ...
      varargin{:} );
