function pfocalqcliqcli_c_statrw(varargin);
% pfocalqcliqcli_c_statrw( [...] );
% QCLIQCLI C stat rw
h = timeplot({'QCLI_C_rw'}, ...
      'QCLIQCLI C stat rw', ...
      'rw', ...
      {'QCLI\_C\_rw'}, ...
      varargin{:} );
