function pfocalbbt(varargin);
% pfocalbbt( [...] );
% Bay Temps
h = timeplot({'CO2_Pamp_T','CO2_SSP_FPGA_T','CO2_24VT','CH4_Pamp_T','CH4_SSP_FPGA_T','CH4_24VT','GDS_Bay_MS_T'}, ...
      'Bay Temps', ...
      'Temps', ...
      {'CO2\_Pamp\_T','CO2\_SSP\_FPGA\_T','CO2\_24VT','CH4\_Pamp\_T','CH4\_SSP\_FPGA\_T','CH4\_24VT','GDS\_Bay\_MS\_T'}, ...
      varargin{:} );
