function pfocalwgpswhkt(varargin);
% pfocalwgpswhkt( [...] );
% Wind HK d Time
h = timeplot({'Wind_mlf_time'}, ...
      'Wind HK d Time', ...
      'd Time', ...
      {'Wind\_mlf\_time'}, ...
      varargin{:} );
