function pfocalwgpsicmhkm(varargin);
% pfocalwgpsicmhkm( [...] );
% ICM HK Mode
h = timeplot({'ICM_mode'}, ...
      'ICM HK Mode', ...
      'Mode', ...
      {'ICM\_mode'}, ...
      varargin{:} );
