function pfocalgdscoehkn(varargin);
% pfocalgdscoehkn( [...] );
% COE HK Nreads
h = timeplot({'GDS_COE_Nreads'}, ...
      'COE HK Nreads', ...
      'Nreads', ...
      {'GDS\_COE\_Nreads'}, ...
      varargin{:} );
