function pfocalmebchoec(varargin);
% pfocalmebchoec( [...] );
% ME Bay CH4 OE Current
h = timeplot({'CH4_OE_OutputCurrent'}, ...
      'ME Bay CH4 OE Current', ...
      'Current', ...
      {'CH4\_OE\_OutputCurrent'}, ...
      varargin{:} );
