function pfocalhkmechechqcle(varargin);
% pfocalhkmechechqcle( [...] );
% ME CH4 Errors CH4 QCL Errors
h = timeplot({'CH4_QCL_ErrorNumber','CH4_QCL_ErrorInstance','CH4_QCL_ErrorParameter'}, ...
      'ME CH4 Errors CH4 QCL Errors', ...
      'CH4 QCL Errors', ...
      {'CH4\_QCL\_ErrorNumber','CH4\_QCL\_ErrorInstance','CH4\_QCL\_ErrorParameter'}, ...
      varargin{:} );
