function pfocalwgpsgpshknns(varargin);
% pfocalwgpsgpshknns( [...] );
% GPS HK N N Sats
h = timeplot({'GPS_N_Sats'}, ...
      'GPS HK N N Sats', ...
      'N Sats', ...
      {'GPS\_N\_Sats'}, ...
      varargin{:} );
