function pfocalwgpsicmhks(varargin);
% pfocalwgpsicmhks( [...] );
% ICM HK Scale
h = timeplot({'ICM_fsc'}, ...
      'ICM HK Scale', ...
      'Scale', ...
      {'ICM\_fsc'}, ...
      varargin{:} );
