function pfocalgdsgdshks(varargin);
% pfocalgdsgdshks( [...] );
% GDS HK Status
h = ne_dstat({
  'Pkg_coll', 'GDS_Cmd_Stat', 0; ...
	'Busy', 'GDS_Cmd_Stat', 1; ...
	'Bus', 'GDS_Cmd_Stat', 2; ...
	'Bad_addr', 'GDS_Cmd_Stat', 3; ...
	'Arb_lost', 'GDS_Cmd_Stat', 4; ...
	'Nack', 'GDS_Cmd_Stat', 5 }, 'Status', varargin{:} );
