function pfocaldacschp(varargin);
% pfocaldacschp( [...] );
% CH4 P
h = timeplot({'CH4_CellP','CH4_CellP'}, ...
      'CH4 P', ...
      'P', ...
      {'CH4\_CellP','CH4\_CellP'}, ...
      varargin{:} );
