function pfocalcoedcoehkms(varargin);
% pfocalcoedcoehkms( [...] );
% uD COE HK M Sat
h = ne_dstat({
  'MSat0_CO2', 'uD_COE_stat0', 2; ...
	'MSat1_CO2', 'uD_COE_stat1', 2; ...
	'MSat2_CO2', 'uD_COE_stat2', 2; ...
	'MSat3_CO2', 'uD_COE_stat3', 2; ...
	'MSat4_CO2', 'uD_COE_stat4', 2; ...
	'MSat5_CO2', 'uD_COE_stat5', 2; ...
	'MSat6_CO2', 'uD_COE_stat6', 2; ...
	'MSat7_CO2', 'uD_COE_stat7', 2 }, 'M Sat', varargin{:} );
