function pfocalmecofgv(varargin);
% pfocalmecofgv( [...] );
% ME CO2 Fwd Gas Voltage
h = timeplot({'Fwd_Gas_OutputVoltage'}, ...
      'ME CO2 Fwd Gas Voltage', ...
      'Voltage', ...
      {'Fwd\_Gas\_OutputVoltage'}, ...
      varargin{:} );
