function pfocalqcli_qcli_m_statflash(varargin);
% pfocalqcli_qcli_m_statflash( [...] );
% QCLI M stat flash
h = timeplot({'QCLI_M_flash'}, ...
      'QCLI M stat flash', ...
      'flash', ...
      {'QCLI\_M\_flash'}, ...
      varargin{:} );
