function pfocalqcli_qcli_c_statflash(varargin);
% pfocalqcli_qcli_c_statflash( [...] );
% QCLI C stat flash
h = timeplot({'QCLI_C_flash'}, ...
      'QCLI C stat flash', ...
      'flash', ...
      {'QCLI\_C\_flash'}, ...
      varargin{:} );
