function pfocalhkmpchkstale(varargin);
% pfocalhkmpchkstale( [...] );
% MPC HK Stale
h = timeplot({'M_AbsP_Stale','MPC_Stale'}, ...
      'MPC HK Stale', ...
      'Stale', ...
      {'M\_AbsP\_Stale','MPC\_Stale'}, ...
      varargin{:} );
