function pfocaldacsdcoptt(varargin);
% pfocaldacsdcoptt( [...] );
% uDAC Su DCO2 PT T
h = timeplot({'uDCO2_OE_T','uDCO2_LH_T'}, ...
      'uDAC Su DCO2 PT T', ...
      'T', ...
      {'uDCO2\_OE\_T','uDCO2\_LH\_T'}, ...
      varargin{:} );
