function pfocalqcliqclicssp(varargin);
% pfocalqcliqclicssp( [...] );
% QCLI C SSP
h = timeplot({'SSP_C_Status'}, ...
      'QCLI C SSP', ...
      'SSP', ...
      {'SSP\_C\_Status'}, ...
      varargin{:} );
