function pfocalwgpswhkn(varargin);
% pfocalwgpswhkn( [...] );
% Wind HK N samples
h = timeplot({'Wind_N_samples'}, ...
      'Wind HK N samples', ...
      'N samples', ...
      {'Wind\_N\_samples'}, ...
      varargin{:} );
