function pfocalhkmebfgv(varargin);
% pfocalhkmebfgv( [...] );
% ME Bay Fwd Gas Voltage
h = timeplot({'Fwd_Gas_OutputVoltage'}, ...
      'ME Bay Fwd Gas Voltage', ...
      'Voltage', ...
      {'Fwd\_Gas\_OutputVoltage'}, ...
      varargin{:} );
