function pfocalmebcooev(varargin);
% pfocalmebcooev( [...] );
% ME Bay CO2 OE Voltage
h = timeplot({'CO2_OE_OutputVoltage'}, ...
      'ME Bay CO2 OE Voltage', ...
      'Voltage', ...
      {'CO2\_OE\_OutputVoltage'}, ...
      varargin{:} );
