function pfocalgdscoehkaiic(varargin);
% pfocalgdscoehkaiic( [...] );
% COE HK AI I2C
h = timeplot({'GDS_COE_I2C_Status'}, ...
      'COE HK AI I2C', ...
      'AI I2C', ...
      {'GDS\_COE\_I2C\_Status'}, ...
      varargin{:} );
