function pfocalcoedcoeptrhp(varargin);
% pfocalcoedcoeptrhp( [...] );
% uD COE PTRH P
h = timeplot({'uD_COE_OE_P','uD_COE_LH_P'}, ...
      'uD COE PTRH P', ...
      'P', ...
      {'uD\_COE\_OE\_P','uD\_COE\_LH\_P'}, ...
      varargin{:} );
